version: '3'

services:
  mysql:
    image: mysql:8
    hostname: mysql
    environment:
      MYSQL_DATABASE: novex
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3307:3307'

  php-fpm:
    image: webdevops/php-dev:8.1
    hostname: php-fpm
    volumes:
      - './:/app'
    working_dir: '/app'
    depends_on:
      - mysql

  nginx:
    image: webdevops/nginx
    hostname: nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - '81:80'
    volumes:
      - './:/app'
    depends_on:
      - php-fpm

  composer:
    restart: 'no'
    image: composer:latest
    command: install --ignore-platform-reqs
    working_dir: /app
    volumes:
      - './:/app'